### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by MasterKiller1239** [MasterKiller1239/RandomMovement#1]
- [x] Project created on Unity version 2020.3.x 

Part 1:
- [x] Navmesh
- [x] UI(units hp)
- [x] Units AI movement
- [x] Units Spawner
- [x] Units HP handler
- [x] Outline on clicked Units
- [x] UI-HP handler communication

Part 2(Marko Polo):
- [x] UI
- [x] Marko Polo checker
